# their theme is sooooooo good
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
source: public

# Header links
aux_links_new_tab: true
aux_links:
  "GitHub":
    - "https://github.com/BirbJS/Birb"
  "NPM":
    - "https://npmjs.com/package/birb"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/BirbJS/Documentation"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
